issue: #300  I have made the improvements in the code
kantord/SeaGOAT pull request #349
Opened 2023-10-21 14:02 UTC by Cretus-iosDev

#300

2023-10-21 19:53 UTC, kantord requested changes

2023-10-21 19:53 UTC, kantord commented on tests/test_server.py
> -def test_status_endpoint_with_some_files_not_analyzed(server):
I guess in the end it would be nice to still keep `test_status_endpoint_with_some_files_not_analyzed` while also including the test that you wrote

2023-10-22 07:38 UTC, kantord commented
also it seems like the tests are not passing, please fix them :pray:

2023-10-22 13:03 UTC, Cretus-iosDev commented
> also it seems like the tests are not passing, please fix them 🙏

ok i'll generate the new PR

2023-10-22 13:04 UTC, closed without merging